### ISSUE TITLE
Operations used correctly

### ISSUE THREAD

**Issue by mixonic** [aptible/dashboard.aptible.com#129]
This ticket audits our use of operations to ensure we are using them correctly across the board.

* Apps
  * [ ] ~~Creation in wizard~~ (does not require operation)
  * [ ] ~~Provisioning upon wizard completion~~ (happens at deploy)
  * [ ] ~~Provisioning upon email verification~~ (happens at deploy)
  * [ ] ~~Creation~~ (happens at deploy)
  * [ ] ~~Update~~ (unimplemented, possible to change handle, but there is no operation)
  * [x] Destruction https://github.com/aptible/diesel.aptible.com/blob/master/app/app/deprovision/route.js#L18
* Services
  * [x] Update (scaling container count) (#141) https://github.com/aptible/diesel.aptible.com/blob/master/app/app/services/route.js#L18
* Databases
  * [ ] ~~Creation in wizard~~ (does not require operation)
  * [x] Provisioning upon wizard completion https://github.com/aptible/diesel.aptible.com/blob/master/app/welcome/payment-info/route.js#L99
  * [x] Provisioning upon email verification https://github.com/aptible/diesel.aptible.com/blob/master/app/verify/route.js#L18
  * [x] Creation https://github.com/aptible/diesel.aptible.com/blob/master/app/databases/new/route.js#L28
  * [ ] ~~Update~~ (unimplemented, possible to change handle, but there is no operation because we will not offer the chance to change disk size)
  * [x] Destruction https://github.com/aptible/diesel.aptible.com/blob/master/app/database/deprovision/route.js#L18
* VHosts
  * [x] Creation https://github.com/aptible/diesel.aptible.com/blob/master/app/app/vhosts/new/route.js#L35
  * [x] Update https://github.com/aptible/diesel.aptible.com/blob/master/app/app/vhosts/edit/route.js#L27
  * [x] Destruction (ref'd #123) https://github.com/aptible/diesel.aptible.com/blob/master/app/components/delete-vhost/component.js#L15
* Log Drains (discussed in #101) (issue: #138)
  * [x] Creation https://github.com/aptible/diesel.aptible.com/blob/master/app/stack/log-drains/new/route.js#L20
  * [ ] ~~Update~~ (should update the log drain, then create an operation for "configure" — the UI does not currently allow a user to edit a log drain)
  * [ ] ~~Destruction~~ (unimplemented, and should not be)

* [ ] After deprovision operations (app, databases, log drains, vhosts) we propose that the API is responsible for deleting the resource after deprovisioning, and diesel will destroy the local version of that resource after the deprovision is complete (and no issue a DELETE API call for it).
  * server-side index endpoints will need to hide deprovisioning/deprovisioned entries
  * log drains don't have a button for delete, they can stay that way

**Comment by mixonic** [comment]
In the longer run, @fancyremarker wants to pursue something like this: https://github.com/aptible/api.aptible.com/issues/103 it really seems like what is lacking is maybe just solid API documentation. All these notes can help with that.

**Comment by bantic** [comment]
Updated scribble out "Log Drains - Update" as the diesel UI as implement (and planned, I believe) does not provide the facility to edit a log drain. @sandersonet can you correct me if I'm wrong?

**Comment by sandersonet** [comment]
All required operations are accounted for.
