### ISSUE TITLE
Organization environments page styles

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#241]
- [x] Index
- [x] Show

**Comment by bantic** [comment]
@sandersonet Did we decide to remove the "environments" link from org settings for now? Should we close this issue?

**Comment by sandersonet** [comment]
Yeah, this isn't in scope for launch but will probably need addressed soon after.  I removed the milestone.

**Comment by sandersonet** [comment]
Fixed by #327
