### ISSUE TITLE
Organization billing section styles

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#243]
- [ ] Overview
- [x] Plan
- [x] Payment Method
- [ ] Invoices

**Comment by mixonic** [comment]
@sandersonet I think this is also not part of the immediate/launch organizations milestone, yes? We discussed that this is largely done manually today, and will simply continue to be manual after diesel becomes dashboard.

Dropping from the milestone but please let me know if I've missed something.

**Comment by sandersonet** [comment]
You are correct, thanks.

**Comment by sandersonet** [comment]
Closing in favor of separate Overview and Invoices screens.
