### ISSUE TITLE
Performance improvement burndown

### ISSUE THREAD

**Issue by fancyremarker** [aptible/dashboard.aptible.com#273]
Starting to log items for review/correction here:

* [x] Fingerprinted assets (e.g., /assets/vendor-4bf4303846297482e833395b9588e8e4.css) should have far-future cache headers (right now they've got `Cache-Control: no-cache`)
* [x] Enable 304 caching
* [x] Compressing https://dashboard.aptible.com/ could save 2.6KiB (62% reduction). `index.html` is not served gzipped from CF. Addressed by https://github.com/aptible/dashboard.aptible.com/pull/356.

**Comment by mixonic** [comment]
`divshot.production.json` differs from staging in this regard, be sure to check prod.

**Comment by rwjblue** [comment]
Both `vendor.js` and `vendor.css` have far future `Cache-Control` values (`Cache-Control:max-age=63072000, public`) for both initial response (200) and cached refresh (304).

Updating checklist above with results of running Google's PageSpeed against the app.

**Comment by fancyremarker** [comment]
:+1: Thanks @rwjblue !
