### ISSUE TITLE
[object Object] red bar when trying to create role

### ISSUE THREAD

**Issue by aaw** [aptible/dashboard.aptible.com#279]
Here's what the red bar looked like:

![pasted_image_at_2015_04_23_02_10_pm](https://cloud.githubusercontent.com/assets/274931/7306422/1a38ea2e-e9d3-11e4-949a-665a4336eac5.png)

I couldn't reproduce with my own account, but suspect it has something to do with a role change that happened immediately preceding this operation. The customer in question had dashboard open while another user added him to a privileged role so that he could create a role, then the customer attempted to add a role and got this message at the top of the page. The role creation seemed to work okay, so it looks like mostly a cosmetic concern.

**Comment by fancyremarker** [comment]
SALMON SLAPPED!

**Comment by sandersonet** [comment]
Also seeing this on environment creation cc @fancyremarker
