### ISSUE TITLE
Fix vertical spacing on service container counts

### ISSUE THREAD

**Issue by chasballew** [aptible/dashboard.aptible.com#281]
![screen shot 2015-05-04 at 10 13 04 am 2](https://cloud.githubusercontent.com/assets/3422584/7460519/3ccb5b00-f269-11e4-9a6b-0ebd57b782e8.png)

**Comment by wcpines** [comment]
![image](https://cloud.githubusercontent.com/assets/11494834/7596526/4350d622-f8bc-11e4-9e48-e64397f237d3.png)

**Comment by sandersonet** [comment]
Fixed by #327
