### ISSUE TITLE
Environment Management

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#290]
A user should be able to view and create environments

* Environment index [page 306](https://drive.google.com/file/d/0Bxuaj2I3HLq-bVRqSEpRbVk5M1k/view?usp=sharing)
* Environment create [page 307a](https://drive.google.com/file/d/0Bxuaj2I3HLq-SmJnRUtUcWtuTGs/view?usp=sharing) [page 307b](https://drive.google.com/file/d/0Bxuaj2I3HLq-UFdBRUVqU0hMejg/view?usp=sharing)

**Comment by mixonic** [comment]
Closed by https://github.com/aptible/dashboard.aptible.com/pull/302
