### ISSUE TITLE
Billing Management

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#291]
A user should be able to manage their own billing settings

* [x] Billing/Plan [page 310a](https://drive.google.com/file/d/0Bxuaj2I3HLq-WmFsYTZfUFhMcTg/view?usp=sharing) [page 310b](https://drive.google.com/file/d/0Bxuaj2I3HLq-WEhYc0RHR1hUdGs/view?usp=sharing) (PR: #309)
* [x] display billing header (card type, next invoice date, next 4 digits) (PR https://github.com/aptible/dashboard.aptible.com/pull/310)
* [x] Billing/Payment Method [page 311](https://drive.google.com/file/d/0Bxuaj2I3HLq-eUlDZ01xbWVXeDg/view?usp=sharing) (PR: #330)

Other billing screens (not part of this issue):
* Billing/Overview [page 309](https://drive.google.com/file/d/0Bxuaj2I3HLq-UlRkdVpuNzJzYW8/view?usp=sharing)
* Billing/Invoice History [page 312](https://drive.google.com/file/d/0Bxuaj2I3HLq-cERUeDJBVzFIWTQ/view?usp=sharing)

**Comment by sandersonet** [comment]
@samyount @chasballew Feel free to weigh in on these screens and their copy.  

When upgrading, we probably want to throw up a confirmation modal clarifying they'll be charged the $499 immediately.

**Comment by chasballew** [comment]
@sandersonet - The billing can happen immediately, but the stack creation and contract/BAA piece are still async. The contracts are formatted and ready to be triggered through the Echosign API, per #151.

**Comment by sandersonet** [comment]
Good point @chasballew .  Do you have thoughts on how we can word this in the confirmation modal?  Something to the effect of "Once you upgrade, an Aptible Account Manager will contact you with instructions for signing a BAA and using your new PHI-ready environment.  Your card will be charged immediately."  cc @bantic

**Comment by chasballew** [comment]
SGTM

**Comment by bantic** [comment]
updated the modal:

![image](https://cloud.githubusercontent.com/assets/2023/7870415/34c7915c-0557-11e5-8330-18a37158f3bc.png)

**Comment by sandersonet** [comment]
Closing this as finished.  Opening separate tickets for Overview and Invoices screens.
