### ISSUE TITLE
Nav back to apps and database listings

### ISSUE THREAD

**Issue by steakchaser** [aptible/dashboard.aptible.com#297]
UX suggestion: Right now, when you are viewing the details of a specific app or database, it's not possible to go to the /apps or /databases index listings.  To get back to these views you have to use the top nav "Apps and Databases", and then select the "Apps" or "Databases" pill - this is confusing.  Might be better to make the left nav headings links

**Comment by sandersonet** [comment]
@steakchaser Thanks for this suggestion, this is now implemented and deployed to production.
