### ISSUE TITLE
Use analytics.group() rather than company trait to define companies in Intercom

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#338]

**Comment by wcpines** [comment]
@sandersonet  Will the group attribute == company?

**Comment by gib** [comment]
Slated this for my Monday pairing session with @fancyremarker.

**Comment by wcpines** [comment]
Siiiiick

**Comment by sandersonet** [comment]
Fixed by https://github.com/aptible/auth.aptible.com/commit/f1bdadf3ca2ed8b415848a8e3648623461f2d118#diff-7e8d8484265aba2e9c57adeebe1a83d1
