### ISSUE TITLE
Add GIS as an option when provisioning Postgres

### ISSUE THREAD

**Issue by chasballew** [aptible/dashboard.aptible.com#351]
Enable the extension (which is [already supported](https://github.com/aptible/docker-postgresql/issues/1)) and update the connection string in the dashboard to use the postgis:// prefix

**Comment by fancyremarker** [comment]
I don't think we want to do this. It's easy enough for a client to run `CREATE EXTENSION postgis`. ActiveRecord, for example, will do this via db/schema.rb iff. PostGIS is required. Closing, but let me know if I'm missing something.
