### ISSUE TITLE
ENV-configurable Auth/API backends

### ISSUE THREAD

**Issue by fancyremarker** [aptible/dashboard.aptible.com#363]
See https://github.com/fancyremarker/dashboard.aptible.com/pull/1#issuecomment-120193409

> One question, which I think we should address in a separate issue, is how to best configure different Auth/API backends for custom Dashboard deployments (e.g., auth-rwjblue.aptible-sandbox.com)

**Comment by sandersonet** [comment]
Fixed by https://github.com/aptible/dashboard.aptible.com/pull/412
