### ISSUE TITLE
Adding an ElasticSearch log drain without existing DB is weird

### ISSUE THREAD

**Issue by rwjblue** [aptible/dashboard.aptible.com#371]
Currently shows an empty select box:

![screenshot](http://monosnap.com/image/02SY4GXboel3RMoJbEHAb5lSlDy2ja.png)

Would be nice to have a link to add a database.

**Comment by rwjblue** [comment]
A few things we could do when an Elasticsearch database is not already setup:

1. Make the Elasticsearch radio button disabled
2. Replace select box with a link to "Add Database"
3. Add a link to the support article on setting up an Elasticsearch log drain
4. All of the above.

Thoughts?

**Comment by blakepettersson** [comment]
I'm all for 2) and 3). I wanted to do those two when I did the dropdown but my Ember-foo was (is?) not strong enough.
