### ISSUE TITLE
Multiple redundant domains provisioned

### ISSUE THREAD

**Issue by boydgreenfield** [aptible/dashboard.aptible.com#378]
Earlier today, I provisioned a domain for `beta.onecodex.com`. I definitely clicked a number of times as there was some latency in my connection and no visual feedback that the request had gone through. Eventually, the page gave me a green success bar, as well as two red error bars with JS messages (that I didn't record, sorry).

Later, I refreshed the domains page and saw that I'd inadvertently launched ~7 domain requests with the same name. I'm not sure if this actually did it on the backend, but FYI this is what it looked like:

![image](https://cloud.githubusercontent.com/assets/535969/8768421/f669074a-2e34-11e5-96b4-9789d5a4b782.png)

As a user, I would expect multiple requests with the same name to fail.
 

Ps. If I should open these on aptible/support or elsewhere, just let me know :smile:

**Comment by boydgreenfield** [comment]
(Note that I hid the ELB url in the above image; that loaded just fine)

**Comment by rwjblue** [comment]
I completely agree that you should not have been able to create multiple entries for the same domain like this.  I'm going to label this and try to dig into exactly what is happening internally to see how easy/hard the fix is.

Thanks for reporting!

**Comment by boydgreenfield** [comment]
Sounds good, and not a problem. Have some other VHOST-related questions
I'll follow up with you folks on Slack about tomorrow.
