### ISSUE TITLE
Error displayed when saving organization contact settings

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#381]
cc @blakepettersson 

![screenshot 2015-07-20 11 08 37](https://cloud.githubusercontent.com/assets/884151/8779139/bbbbe630-2ecf-11e5-9ba0-9ded65d25a23.png)

Organization attribute changes are saved successfully, however billing contact changes are not.

**Comment by blakepettersson** [comment]
The issue is that the invoice date is null for the Aptible organization. In PR aptible/ember-cli-aptible-shared#31 the `nextInvoiceDate` is excluded from being serialized as JSON, which should fix this issue.

**Comment by sandersonet** [comment]
Fixed by aptible/ember-cli-aptible-shared#31
