### ISSUE TITLE
Add ability to remove/restart log drains

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#383]
For now:
* [ ] Delete the log drain
* [ ] Create `configure` operation on remaining log drain (https://github.com/aptible/api.aptible.com/blob/master/lib/management_helpers.rb#L55)

Once deprovision/provision operations are supported:
* [ ] Create `deprovision` operation for log drain to delete
* [ ] Create `provision` operation for log drain to create

**Comment by fancyremarker** [comment]
Also, we should provide a way to simply re-configure ("refresh") an existing log drain.
