### ISSUE TITLE
SSH Keys persist after removing account from organization

### ISSUE THREAD

**Issue by calebboyd** [aptible/dashboard.aptible.com#385]
Since a user object is potentially multi-tenant, when they are removed form an organization their SSH keys stick around. Need a way to remove these or manage ssh keys at an org level for robots.

**Comment by sandersonet** [comment]
Thanks for this @calebboyd.  After some internal discussion, we believe that everything is working correctly and that the recommended procedure for having org-level SSH keys would be to create a "robot" user as described in both the [Circle CI guide](https://github.com/aptible/support/blob/9412a03fbae882e6e491dc3d314050dc9efd3b05/source/topics/paas/how-to-set-up-circle-ci.md) and the [Travis CI guide](https://github.com/aptible/support/blob/9412a03fbae882e6e491dc3d314050dc9efd3b05/source/topics/paas/how-to-set-up-travis-ci.md).
