### ISSUE TITLE
User should not be able to create empty Elasticsearch log drain

### ISSUE THREAD

**Issue by fancyremarker** [aptible/dashboard.aptible.com#388]
Repro: from an environment with no Elasticsearch databases,

* Provision an Elasticsearch log drain.

We should also validate against this at the API level.

**Comment by rwjblue** [comment]
This is kind of a duplicate of https://github.com/aptible/dashboard.aptible.com/issues/371 I believe.  We can keep this if you prefer...

**Comment by fancyremarker** [comment]
Nope, this is a dupe. Closing, thanks!
