### ISSUE TITLE
Confusing select box with multiple certificates having the same Common Name

### ISSUE THREAD

**Issue by fancyremarker** [aptible/dashboard.aptible.com#405]
![image](https://cloud.githubusercontent.com/assets/156030/9340191/5d17ec92-45bc-11e5-8c7f-69c5647f4318.png)

cc: @sandersonet 

We can run a query on production to see how much of an actual effect this would have.

**Comment by sandersonet** [comment]
Do you have a suggestion for an alternative way present the available certificates?

**Comment by fancyremarker** [comment]
One option would be to list the apps (through VHOSTs) each certificate is attached to. Also, as you mentioned, expiry would be a good idea.

**Comment by sandersonet** [comment]
Additional details we could provide:

* Cert expiry
* App handles currently using cert
* Common names from entire certificate chain
