### ISSUE TITLE
Billing Contact field does not update billing contact

### ISSUE THREAD

**Issue by wcpines** [aptible/dashboard.aptible.com#406]
Telepharm updated their billing contact after the previous member left.  I asked the current billing role member to repeat this a second time.  He included a [screenshot](https://files.slack.com/files-pri/T02NH77TU-F09ADR3F1/pasted_image_at_2015_08_19_09_58_am.png) 

The Stripe subscription contact remains kent@telepharm.com.  Billing API matches:

```
irb(main):015:0> bd.billing_contact_id_was
=> "8ec3d924-8ac1-4b9a-8722-b92aacfc3be5"
irb(main):016:0> bd.billing_contact_id    
=> "8ec3d924-8ac1-4b9a-8722-b92aacfc3be5"
```

I would think expected behavior is to change the billing contact in Stripe.  

@blakepettersson or @sandersonet  either of you confirm?

**Comment by sandersonet** [comment]
Yep, updating the billing contact should update the stripe customer's email attribute.  Assigning to @blakepettersson

**Comment by blakepettersson** [comment]
Fixed with aptible/billing.aptible.com#55.
