### ISSUE TITLE
Raven.js swallows all exceptions in development

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#411]
Currently impossible to get an error/stack trace in development when raven.js is loaded.

**Comment by rwjblue** [comment]
Raven should be disabled locally by default.  Are you seeing it enabled when running local development?

**Comment by sandersonet** [comment]
Yep, the only way we could prevent it from swallowing an undefined `asdf();` exception was to comment out the CDN from the config: https://github.com/aptible/dashboard.aptible.com/blob/master/config/environment.js#L39
