### ISSUE TITLE
Usability issues with adding people to a new account/org

### ISSUE THREAD

**Issue by HowardLook** [aptible/dashboard.aptible.com#418]
Create a new Aptible account. Wanted to add other engrs to the account. Could figure out how. Here's why:
1) When I hover over my name in the upper right, the entire rectangle highlights.

![image](https://cloud.githubusercontent.com/assets/3392037/9535955/97104bd0-4cdb-11e5-8ba5-32e1ab3e1289.png)

That leads me to believe that the entire area is one big hit spot. I now see that the down triangle gives me a different context menu. Suggestions 1 and 2: Use a clearly separated affordance, like a vertical line between my name and the down triangle. OR make that menu appear always.

Hitting the big button (not the triangle) takes me to my personal account settings, but there's no indication of my domain/company here:

![image](https://cloud.githubusercontent.com/assets/3392037/9535971/bfff67f6-4cdb-11e5-9d4c-86c1ecfe1e37.png)

Suggestion 3: Put "Tidepool Settings" on the panel to the left.

**Comment by chasballew** [comment]
Great suggestions, thank you!

**Comment by sandersonet** [comment]
Hey @HowardLook, thanks for reporting this.  You're right, that experience isn't very intuitive.

**Comment by HowardLook** [comment]
No problem. I just call 'em like I see 'em. Glad to see that most (all?) of
your stuff is open on GitHib. Nice work!

**Comment by gib** [comment]
@HowardLook - I'm a T1 Diabetic myself and hope that Aptible can help speed the Tidepool's path to success. Very excited about your work!
