### ISSUE TITLE
No way to see databases/apps past first page of pagination

### ISSUE THREAD

**Issue by fancyremarker** [aptible/dashboard.aptible.com#428]

**Comment by sandersonet** [comment]
@rwjblue -- Want to take a look at this?  We already [paginate app.operations](https://github.com/aptible/ember-cli-aptible-shared/blob/master/app/mixins/routes/paginated-operations.js) so it shouldn't be much to port this over to apps/dbs.

**Comment by chasballew** [comment]
We might also consider adjusting the size of the database divs. (That was a suggestion from several customers.)

**Comment by fancyremarker** [comment]
@chasballew: Adjusting them to be larger or smaller?

**Comment by chasballew** [comment]
Smaller.
