### ISSUE TITLE
Changes to Procfile are not reflected in app#services view

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#447]
The `command` value in `app#services` route is not updated after changes to the app's `Procfile`.

Thanks @evan-007

**Comment by evan-007** [comment]
I just pushed a second build with the same config and the command was updated in the dashboard.

**Comment by sandersonet** [comment]
Tested this repeatedly on production and am unable to reproduce.  I believe the issue is that we don't reload services from the server on each page view and instead load from memory.  A hard refresh on the services page always seems to render the correct Procfile command.

I'll close this and open a new issue for upgrading to Ember Data 2.0, which has background loading of stale resources.
