### ISSUE TITLE
Integrate Clearbit API so we can "enhance" signups

### ISSUE THREAD

**Issue by samyount** [aptible/dashboard.aptible.com#476]
Use the [Clearbit Slack Gem] (https://github.com/clearbit/clearbit-slack) to enhance new dev account signups.  Post these to a new Slack channel (#clearbit?).  Ideally we could also save the lookup information somewhere so that we could populate it elsewhere without having to use lots more API queries.

**Comment by samyount** [comment]
Assigning to @gib as he and I talked it about a bunch and was on the call with Clearbit with me

**Comment by gib** [comment]
:+1: Thanks @samyount

**Comment by gib** [comment]
Closing. We may circle back.
