### ISSUE TITLE
Dashboard Logdrain status should be updated w/o refresh

### ISSUE THREAD

**Issue by wcpines** [aptible/dashboard.aptible.com#483]
Provisioning a papertrail logdrain shows a green spinner and 'provisioning' status, but this remains even after  the API shows `status: provisioned`

Afaik there should be polling/update event. Otherwise a page refresh is necessary.

**Comment by gib** [comment]
Thank you @wcpines, I think we've discussed it and some possible solutions. Glad it's tracked here!

**Comment by sandersonet** [comment]
Log drains are already [provisionable](https://github.com/aptible/ember-cli-aptible-shared/blob/master/app/mixins/models/provisionable.js), so this is as simple as adding `reloadWhileProvisioning: true` to the model like [we already do for databases](https://github.com/aptible/ember-cli-aptible-shared/blob/master/app/models/database.js#L18).
