### ISSUE TITLE
Add LICENSE file.

### ISSUE THREAD

**Issue by rwjblue** [aptible/dashboard.aptible.com#484]
I believe the license should be MIT.

@fancyremarker - Can you confirm?

**Comment by fancyremarker** [comment]
Confirmed, all open source repos should be MIT. All closed-source repos should have no LICENSE.md file and call out "All rights reserved" in the README.

**Comment by fancyremarker** [comment]
Dupe of aptible/support#136, but leaving open.

**Comment by rwjblue** [comment]
Yeah, sorry about the duplication.  I hadn't noticed https://github.com/aptible/support/issues/136 until you mentioned it in slack.
