### ISSUE TITLE
Domains listed in environment metadata don't update correctly when changing stacks

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#496]

**Comment by gib** [comment]
This is still an issue. Easily reproduced on production. The totals are correct, but the listed domains are not. Thanks for the find @chasballew.

**Comment by chasballew** [comment]
I found it

![](http://www.summerbeats.com.br/img/golden-ticket.gif)

**Comment by gib** [comment]
I love this
