### ISSUE TITLE
Changing SSL cert requires hard refresh to show new cert in /stacks/:id/certificates

### ISSUE THREAD

**Issue by evan-007** [aptible/dashboard.aptible.com#499]
I had to change the SSL cert for our production app.

  1. Add the new cert in `/stacks/:id/certificates`
  2. Select the new cert in `/apps/:id/vhosts/:id/edit` and save
  3. Flash message that it changed successfully appears
  4. Click back to `apps/:id/vhosts/:id/edit` to verify that new cert is listed. Old cert still shows.
  5. Shift + refresh the page, now the new cert is showing.

Don't know if it's important, but I was worried that the changes weren't actually saved or I had an issue with my cert. Does it just take a few minutes for the change to propagate?

**Comment by gib** [comment]
Notes to self:
1. Ensure vhosts and certs have the correct relationship to cascade updates
2. Could also force certificates route to always reload as an alt fix

**Comment by sandersonet** [comment]
@gib, here is an example of forcing a reload in a model hook: https://github.com/aptible/dashboard.aptible.com/blob/52050f3b443a73cfd88747db7d0fa5ca9537abfe/ap
p/apps/route.js

**Comment by evan-007** [comment]
I think the same thing is happening for DB deprovisioning. I just set one of our staging postgres to deprovision and the dashboard redirects me to `stacks/:id/databases`, but the deprovisioning db is still listed and clicking it gives a 404. Refreshing the page removes it.

**Comment by gib** [comment]
DB deprovisioning is OK, but I'm still seeing the cert bug on staging. The challenge to fix is how to repro locally...

**Comment by sandersonet** [comment]
@gib -- Update your local config/environment.js to use the staging auth/api servers

**Comment by gib** [comment]
:bow: -- thanks @sandersonet!
