### ISSUE TITLE
FTUX databases are not always provisioned

### ISSUE THREAD

**Issue by fancyremarker** [aptible/dashboard.aptible.com#506]
Is `provisionDatabases()` not [always called](https://github.com/aptible/dashboard.aptible.com/blob/e2df50c16c71733f97eb7ef57a0147ac8ab46627/app/verify/route.js#L18)? Are there other paths to verification than through that route?

**Comment by sandersonet** [comment]
This *should* always be called, however given that we do this on the client, it's really impossible to make guarantees.  At least two AJAX requests are called after verification but before provisioning:

1) The user is reloaded to ensure they are `verified: true`
2) Databases are fetched

This leaves a small window while these calls are in flight where a user can close their browser window before the provision operation is created. 

I think the simplest fix is to call `provisionDatabases` on every visit to `database#index`.  We should also update `provisionDatabases` to set the database status to `provisioning`.  I know this happens automatically in sweetness, but we can do it here in memory to force the database to appear in the correct sort row.  It will also automatically set the database up for status update polling.

@gib -- Want to take a stab at this and/or pair?

**Comment by fancyremarker** [comment]
@sandersonet: If there's an easier approach that involves relaxing the rules for creating operations (e.g., allowing for unverified users), LMK.

**Comment by sandersonet** [comment]
That would be easier, but is not necessary.  The databases are already in memory on the databases#index route.  Looping through them and provisioning any that are `pending` should be almost just as easy.

**Comment by skylar-anderson** [comment]
Fixed
