### ISSUE TITLE
Add ability to delete default VHOSTS

### ISSUE THREAD

**Issue by chasballew** [aptible/dashboard.aptible.com#508]
Default VHOST:
![screenshot 2016-01-19 20 55 47](https://cloud.githubusercontent.com/assets/3422584/12439564/0df5414e-beef-11e5-96f6-9e16394d0484.png)

Non-default VHOST:
![screenshot 2016-01-19 20 56 26](https://cloud.githubusercontent.com/assets/3422584/12439572/284e0fbc-beef-11e5-9037-0e3fe6aeb2db.png)

**Comment by sandersonet** [comment]
I don't think this is strictly a UI change, is it @fancyremarker ?

**Comment by fancyremarker** [comment]
@sandersonet: Correct. aptible/api.aptible.com#234 is a precursor to this.

**Comment by blakepettersson** [comment]
Fixed with #551.
