### ISSUE TITLE
Remove Intercom

### ISSUE THREAD

**Issue by gib** [aptible/dashboard.aptible.com#517]
Should be quick with segment.

**Comment by blakepettersson** [comment]
:tada: :balloon:

**Comment by chasballew** [comment]
Let's be sure to update the corresponding welcome drip email. We can still send it through Intercom, or move it to Customer.io. @wcpines

**Comment by wcpines** [comment]
aye-aye

**Comment by wcpines** [comment]
Keep it in intercom but convert to email instead of In-app. SG @chasballew  ?
