### ISSUE TITLE
Add total membership count on a role (summary panel view)

### ISSUE THREAD

**Issue by gib** [aptible/dashboard.aptible.com#592]
<img width="684" alt="screen shot 2016-05-11 at 12 23 30 pm" src="https://cloud.githubusercontent.com/assets/94830/15191736/3ec69eda-1773-11e6-86c2-67e2b29f67fd.png">
Could add "...and 27 more" to the list of small gravatars at the bottom

**Comment by chasballew** [comment]
![screenshot 2016-05-11 12 23 48](https://cloud.githubusercontent.com/assets/3422584/15191796/7e0f2f4e-1773-11e6-8415-0133b7f0d211.png)

In the image above, there are actually 8 members of the role, but only 5 gravatars are displayed.

**Comment by chasballew** [comment]
Alternatively, we could just list out the names/emails in small font. From what I've noticed, not many customers use Gravatars.
