### ISSUE TITLE
STAGING: Cannot add a membership for a user on a role

### ISSUE THREAD

**Issue by gib** [aptible/dashboard.aptible.com#595]
This appears to be a regression in the sheriff / diesel merge. @fancyremarker and I found it while pairing on some role membership updates.

~~This is the last issue that I'm aware of that could prevent staging from being releasable to production.~~

**Comment by gib** [comment]
I can't reproduce this today. Went over it with @fancyremarker and found some other issues with 500s on auth now when trying to add a new user membership to a role.

Investigation ongoing.

**Comment by gib** [comment]
Dashboard has been updated on production and I'm unable to reproduce any issues there. Only reproducible on staging, auth is unreachable, and the console only offers empty (no response) 500 errors.

**Comment by sandersonet** [comment]
I believe this is fixed
