### ISSUE TITLE
Where did osvaldo go?

### ISSUE THREAD

**Issue by sandersonet** [aptible/dashboard.aptible.com#613]
Our error messages are way to harsh without that friendly octopus to tell me it's gonna be OK.

<img width="907" alt="screenshot 2016-05-25 14 24 07" src="https://cloud.githubusercontent.com/assets/884151/15556746/6a865ecc-2284-11e6-9127-8d664e632e24.png">

**Comment by gib** [comment]
WHA?!? 
![](http://s3.amazonaws.com/rapgenius/6lXJRVuoR1iHY3daEnyv_34732412.jpg.jpg)

I hope I didn't do that.

**Comment by sandersonet** [comment]
It's been that way for a long time--I think I did it during a refactor a few months back

**Comment by blakepettersson** [comment]
Oc-to-pus! Oc-to-pus! Oc-to-pus!
