### ISSUE TITLE
Add an "Actions" header to the new member tables

### ISSUE THREAD

**Issue by gib** [aptible/dashboard.aptible.com#633]
The actions in the row only show up on `:hover`.
<img width="1044" alt="screen shot 2016-06-20 at 12 50 05 pm" src="https://cloud.githubusercontent.com/assets/94830/16206405/94046210-36e5-11e6-9785-4b9f2c426060.png">

I have a new set up for a click-able row that could replace this situation for a single "edit" action, like this one:
<img width="1024" alt="screen shot 2016-06-20 at 12 49 26 pm" src="https://cloud.githubusercontent.com/assets/94830/16206403/921c4698-36e5-11e6-892b-a090ccf34a66.png">

**Comment by sandersonet** [comment]
This is fixed by always showing the buttons rather than only on hover.
