### ISSUE TITLE
Release Role Types

### ISSUE THREAD

**Issue by gib** [aptible/dashboard.aptible.com#638]
- [x] Replace panels with a new überpanel / table for the roles ()
- [x] List scopes for a stack in a role
- [x] List members of a role
- [x] Split compliance and platform roles' routes
- [x] Wire up invite to role in header
- [x] Wire up add user to role in header
- [x] type options component (in progress)
- [x] Update role view with sub views for
      - [x] members
      - [x] environments (platform)
      - [x] products (compliance)
      - [x] settings
- [x] Tooltip for role admin (explain admins' abilities... consider different label)
- [x] Remove Member
- [x] Toggle Member Admin
- [x] Remove invitation
- [x] Resend invitation
- [x] Toggle environment permissions
- [x] BillingDetail `allowsPHI` check for role index
- [x] Create Role form, select platform or compliance

BUGS
- [x] Admin Member of compliance role can't edit

MIGRATION NOTES
- [ ] Check for / eliminate duplicate permissions for individual stacks
<img width="997" alt="screen shot 2016-07-11 at 3 17 50 pm" src="https://cloud.githubusercontent.com/assets/94830/16747161/07b3dcfe-477b-11e6-810e-8b2908d54364.png">

FOR FOLLOW UP
- [ ] Put the Create Role form in a modal (look at "Invite Your workforce" in SPD)

**Comment by sandersonet** [comment]
Fixed by #643

**Comment by waleedasif322** [comment]
@sandersonet @gib what does read permissions entail?

**Comment by skylar-anderson** [comment]
@waleedasif322 - "Read" means you can see the environment and resources within it but that you can't create operations against any of the resources.  As an example, you would be able to see what apps and databases are in a given environment, but you wouldn't be able to SSH or deploy any of those apps.  You also wouldn't be able to tunnel to any DB.
