### ISSUE TITLE
Text is toned down because of Webkit Anti-Aliasing

### ISSUE THREAD

**Issue by krallin** [aptible/dashboard.aptible.com#644]
@sandersonet @gib,

It looks like https://github.com/aptible/dashboard.aptible.com/commit/5f384988 introduced `-webkit-font-smoothing: antialiased `, which causes the entire Dashboard to be a little toned down. See:

With it:

![image](https://cloud.githubusercontent.com/assets/1737686/16680769/5505c3e6-44f1-11e6-80f9-ee7a70b025cc.png)

Without:

![image](https://cloud.githubusercontent.com/assets/1737686/16680782/67512252-44f1-11e6-90e6-f55661ba5f36.png)

--

I'm not much of a designer, so I don't really have an opinion, but it did strike me as a little off (possibly because I'm just used to the old style), but I thought I'd just let you know to make sure this is desired! 

(I do feel it makes some things *a little* hard to read tbh)

**Comment by sandersonet** [comment]
I've emboldened any text I've come across that I felt was too light to be visible.  I'm closing this for now, but feel free to re-open if I missed any cases.
