### ISSUE TITLE
Some Role Refactor issues

### ISSUE THREAD

**Issue by krallin** [aptible/dashboard.aptible.com#648]
cc @gib , @fancyremarker 

I did some basic UI testing (invited myself as a platform owner and clicked around). Here are a few UX issues I found:

When I invited myself, the Role I was inviting myself in wasn't shown:

![image](https://cloud.githubusercontent.com/assets/1737686/16868151/5694206a-4a76-11e6-9dfb-1d86a4cd5d4a.png)

After accepting the invitation, I was allowed to navigate to my user and change my permissions. The API doesn't let me actually do it (which is fine), but it results in a somewhat broken UX:

![image](https://cloud.githubusercontent.com/assets/1737686/16868138/501a7a9a-4a76-11e6-932a-71f24799e556.png)

Same problem in another screen (by editing a Role instead of a user):

![image](https://cloud.githubusercontent.com/assets/1737686/16868142/538768c8-4a76-11e6-85d4-eed35906fcab.png)

There's no save button when editing the environments a Role has access to:

![image](https://cloud.githubusercontent.com/assets/1737686/16868141/51bc4392-4a76-11e6-82e1-06ac2c5fbed0.png)

There's a column / tooltip mismatch here:

![image](https://cloud.githubusercontent.com/assets/1737686/16868150/54e13aaa-4a76-11e6-8b3c-ff40ab7e55cd.png)

**Comment by gib** [comment]
Thank you @krallin!! I'm addressing a few of these with feedback from @chas. I'll follow up with some changes today.
