### ISSUE TITLE
Adding Role Member should reload Members

### ISSUE THREAD

**Issue by krallin** [aptible/dashboard.aptible.com#667]
I added myself as a member here, there was a confirmation, but the list of members did not reload:

![image](https://cloud.githubusercontent.com/assets/1737686/17220475/b269292a-54ef-11e6-8733-7dfa299c78a4.png)

cc @gib

**Comment by gib** [comment]
Thank you @krallin, I know exactly when/where I introduced this yesterday. Running too fast / loose.
