### ISSUE TITLE
Users should see if they are a role admin, see who can access a role

### ISSUE THREAD

**Issue by gib** [aptible/dashboard.aptible.com#683]
<img width="1015" alt="screen shot 2016-08-04 at 12 47 37 pm" src="https://cloud.githubusercontent.com/assets/94830/17442277/3c98f014-5af2-11e6-8689-9d6237ca438c.png">

Possible solutions:
- list all admins
- badge owners / admins in the existing list
- call out that you have access to click / manage a role (right now you have to hover, or try and fail to click)

**Comment by sandersonet** [comment]
Rather than having some roles clickable and others that are not, I opted to just let all roles be clickable.  Once on the `role#show` page, the visibility of certain admin features (invite, permissions, etc) is determined by the current user's authorization context.
