### ISSUE TITLE
Removal of security officer user causes 403s

### ISSUE THREAD

**Issue by wcpines** [aptible/dashboard.aptible.com#697]
_First reported [here](https://aptible.zendesk.com/agent/tickets/6800)._

### Observed Behavior:

A user was set as the security officer of an organization. Later that user was removed.  Afterwards, loading Contact Settings page failed, as did the Edit Member action, throwing a 403.  

Dashboard should handle removed users gracefully
### Work-around
Issue was resolved by setting an existing user to the security officer.

**Comment by gib** [comment]
Fixes have been in production for the last week (since Aug 8). The UI disables the remove button (on member edit) and now informs you with a message explaining that a security officer or billing contact must be assigned before removing the current one.

**Comment by wcpines** [comment]
😄
