### ISSUE TITLE
Tab highlights are gone again?

### ISSUE THREAD

**Issue by krallin** [aptible/dashboard.aptible.com#714]
This might be related to the recent path changes we've made, but it looks like tab highlights are gone again in some cases. E.g.: 

![image](https://cloud.githubusercontent.com/assets/1737686/18240726/c3dfccfa-734d-11e6-8019-2c394c71f78e.png)

Here, we'd expect "Apps" to be highlighted. I have tested that this is indeed new on staging (it works as expected on production).

cc @sandersonet @gib

**Comment by sandersonet** [comment]
Yep this was me.  I'll grab, thx
