### ISSUE TITLE
VHOST provision_failed status copy could be improved

### ISSUE THREAD

**Issue by krallin** [aptible/dashboard.aptible.com#715]
![image](https://cloud.githubusercontent.com/assets/1737686/18240781/0d8726d2-734e-11e6-9b70-589ea65ddace.png)

The copy says "... is provision_failed...", which might not be intentional.

cc @blakepettersson

**Comment by sandersonet** [comment]
@krallin Do you mean improved in the sense of just removing the underscore? Or do we actually have more information available to communicate to the user? I'm happy to grab this in either case.

**Comment by krallin** [comment]
@sandersonet really just the copy change. Something like "failed to provision, please contact support" would — I think — work a little better.
