### ISSUE TITLE
Platform Owner cannot modify access toggles on an environment

### ISSUE THREAD

**Issue by gib** [aptible/dashboard.aptible.com#723]

**Comment by sandersonet** [comment]
Fixed on staging

Sent from my iPhone

> On Sep 8, 2016, at 11:08 AM, Gib Reimschüssel <notifications@github.com> wrote:
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
*Disclaimer: This e-mail and any attachments may contain confidential 
information. If you are not the intended recipient, any disclosure, 
copying, distribution or use of any information contained herein is 
strictly prohibited. *

*If you have received this transmission in error, please immediately notify 
security@aptible.com <security@aptible.com> or call (866) 296-5003 and 
destroy the original transmission and any attachments without reading or 
saving.*

**Comment by gib** [comment]
Fixed in https://github.com/aptible/dashboard.aptible.com/pull/712
